# Generated by Django 5.2.3 on 2025-06-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrbanRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='usage_data.region')),
            ],
        ),
        migrations.CreateModel(
            name='RenewableEnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_id', models.CharField(max_length=10, unique=True)),
                ('monthly_usage_kwh', models.FloatField()),
                ('year', models.PositiveIntegerField()),
                ('household_size', models.PositiveIntegerField()),
                ('adoption_year', models.PositiveIntegerField()),
                ('subsidy_received', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('cost_savings_usd', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='usage_data.country')),
                ('energy_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='usage_data.energysource')),
                ('income_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usage_data.incomelevel')),
                ('urban_rural', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usage_data.urbanrural')),
            ],
        ),
    ]
